insert into public.events (
  slug,
  title,
  start_date,
  end_date,
  place,
  city,
  external_url,
  comment,
  tone,
  status,
  registration_deadline,
  tags
) values
  (
    'vibeside-opening',
    'Открытие сезона VibeSide',
    '2026-05-03',
    null,
    'Мега Дыбенко',
    'Санкт-Петербург',
    null,
    'Открытие сезона и старт летнего календаря.',
    'sky',
    'published',
    null,
    array['show', 'opening']
  ),
  (
    'iddc-stage-1',
    'IDDC 1 этап',
    '2026-05-09',
    '2026-05-10',
    'Игора Драйв',
    'Ленинградская область',
    'https://drive-igora.ru/events/iddc/',
    'Главный двухдневный этап с плотной программой.',
    'violet',
    'published',
    null,
    array['drift', 'championship']
  ),
  (
    'mega-drift-may',
    'Дрифт??',
    '2026-05-23',
    null,
    'Мега Дыбенко',
    'Санкт-Петербург',
    null,
    'Нужна верификация названия и финального анонса.',
    'amber',
    'published',
    null,
    array['drift']
  ),
  (
    'turbonoch',
    'Турбоночь',
    '2026-06-06',
    null,
    'Селар Парк',
    'Санкт-Петербург',
    null,
    'Регистрация закрывается за день до старта.',
    'teal',
    'published',
    '2026-06-05',
    array['night', 'meetup']
  ),
  (
    'yurievo-drift',
    'Дрифт??',
    '2026-06-13',
    '2026-06-14',
    'Картодром Юрьево',
    'Великий Новгород',
    null,
    'Поле под точное название пока остается черновым.',
    'amber',
    'published',
    null,
    array['drift', 'regional']
  ),
  (
    'iddc-stage-2',
    'IDDC 2 этап',
    '2026-06-27',
    '2026-06-28',
    'Игора Драйв',
    'Ленинградская область',
    'https://drive-igora.ru/events/iddc/',
    'Ключевой июньский уикенд с высокой посещаемостью.',
    'violet',
    'published',
    null,
    array['drift', 'championship']
  ),
  (
    'sickestwekfest',
    'sickestwekfest',
    '2026-07-04',
    '2026-07-05',
    'Петрозаводск',
    'Петрозаводск',
    'https://www.instagram.com/sickestwekfest?igsh=MWobb2UxbGc4NXh0aQ%3D%3D',
    'Выездной фестиваль, нужен аккуратный визуальный акцент в календаре.',
    'coral',
    'published',
    null,
    array['festival', 'trip']
  ),
  (
    'tsunami',
    'Цунами',
    '2026-07-11',
    null,
    'СПБ',
    'Санкт-Петербург',
    null,
    'Однодневное городское мероприятие.',
    'sky',
    'published',
    null,
    array['city', 'meetup']
  ),
  (
    'garage-fest',
    'Garage Fest',
    '2026-07-18',
    '2026-07-19',
    'Игора Драйв',
    'Ленинградская область',
    null,
    'Фестивальный формат, важен упор на атмосферу и программу.',
    'coral',
    'published',
    null,
    array['festival', 'track']
  ),
  (
    'japlane',
    'JapLane',
    '2026-07-25',
    null,
    'Стадион Динамо',
    'Минск',
    null,
    'Выезд в Минск, пригодится фильтр по городам на следующем этапе.',
    'sky',
    'published',
    null,
    array['trip', 'show']
  ),
  (
    'grounded',
    'Grounded',
    '2026-08-07',
    '2026-08-08',
    'Роза Хутор',
    'Сочи',
    null,
    'Длинная поездка, потенциально отдельная категория для путешествий.',
    'coral',
    'published',
    null,
    array['festival', 'trip']
  ),
  (
    'ofmit',
    'ОФМИТ',
    '2026-08-15',
    null,
    'Охта Молл',
    'Санкт-Петербург',
    'https://t.me/c/2520806743/2662',
    'Ссылка ведет на Telegram-пост с деталями.',
    'teal',
    'published',
    null,
    array['city', 'show']
  ),
  (
    'cars-picnic',
    'Тачки Пикник',
    '2026-08-15',
    '2026-08-16',
    'Лида',
    'Беларусь',
    null,
    'Пересечение дат с ОФМИТ, интерфейс должен показывать два события в день.',
    'amber',
    'published',
    null,
    array['festival', 'trip']
  ),
  (
    'iddc-stage-3',
    'IDDC 3 этап',
    '2026-08-29',
    '2026-08-30',
    'Игора Драйв',
    'Ленинградская область',
    'https://drive-igora.ru/events/iddc/',
    'Финальный этап лета.',
    'violet',
    'published',
    null,
    array['drift', 'championship']
  )
on conflict (slug) do update
set
  title = excluded.title,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  place = excluded.place,
  city = excluded.city,
  external_url = excluded.external_url,
  comment = excluded.comment,
  tone = excluded.tone,
  status = excluded.status,
  registration_deadline = excluded.registration_deadline,
  tags = excluded.tags;

